
name: backend-ci
on:
  push:
    branches: [ "develop", "main" ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/sky-backend
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Unit & API tests
        run: pytest -q

      - name: Generate OpenAPI schema
        run: python manage.py generateschema > openapi.json

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.json

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Trigger infra (DEV) on develop
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/sky-infra
            export DEV_BACKEND_TAG=${{ env.TAG }}
            docker compose -f compose.dev.yml --env-file .env.dev pull dev-backend
            docker compose -f compose.dev.yml --env-file .env.dev up -d dev-backend
